name: animal-crossing-dict

on:
  push:
    branches:
      - main

jobs:
  prod-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm i

      - name: build next app
        run: npm run build

      - name: deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PROD_KEY }}
          HOST: ${{ secrets.EC2_PROD_HOST }}
          USER: ${{ secrets.EC2_PROD_USER }}
        run: |
          echo "$PRIVATE_KEY" > minda.pem
          chmod 600 minda.pem

          # node_modules 제외하고 파일 전송
          rsync -avz --exclude=node_modules --exclude=.git -e "ssh -i minda.pem -o StrictHostKeyChecking=no" . $USER@$HOST:~/animal-crossing-dict/

          # SSH를 통해 EC2에서 명령어 실행
          ssh -i minda.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd ~/animal-crossing-dict
            npm run build
            pm2 restart next-app || pm2 start node --name "next-app" -- .output/server/index.mjs
          EOF
